### ISSUE TITLE
Add Installation instruction to README

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-agenda#15]
This is a request to add installation instructions for the plugin.  This should include installing from binary and instructions on Developing the plugin

**Comment by Stolzenhain** [comment]
Please correct me – otherwise I'll set up a pull request:

## Installation instructions

### A) The quick route:

1. Download the latest `.tar.gz` from the [release channel](/mattermost/mattermost-plugin-agenda/releases)
2. Upload the plugin at Mattermost system console (`/admin_console/plugins/plugin_management`)

### B) Building from source: 

1. Cloning the project
2. running `make` in root (compare [Mattermost starting template](https://github.com/mattermost/mattermost-plugin-starter-template)) to receive the release archive.
3. proceed like A)

--

Note that building from source failed due to a single jest error with babel.

**Comment by jfrerich** [comment]
Hi @Stolzenhain! That is simple and short.  I would suggest also adding the developer method as described here -> https://github.com/mattermost/mattermost-plugin-github.  You can reference the Develop Section.  

Also, feel free to submit the PR and well integrate the changes.  Thank so much!

**Comment by jfrerich** [comment]
Closing.  Instead of listing this in each plugin README, we should add a link to a commonly shared doc.

**Comment by Stolzenhain** [comment]
> Closing. Instead of listing this in each plugin README, we should add a link to a commonly shared doc.

Good idea! Thanks for following up on that.

**Comment by jfrerich** [comment]
Good to see you @Stolzenhain!
